export const BookingStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PAID_ESCROW: 'PAID_ESCROW',
  THAWED: 'THAWED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
}

export const PayoutStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REJECTED: 'REJECTED',
}

export const PAYOUT_HOUR = 18
export const ESCROW_THAW_DAYS = 1
export const PAYOUT_CRON_CONCURRENCY = 5
