export const ADAPTER_KEYS = {
  CARD_INTL: 'CARD_INTL',
  MIR_RU: 'MIR_RU',
  CRYPTO_TRON: 'CRYPTO_TRON',
}

export const INTERNAL_INTENT_STATUSES = {
  CREATED: 'CREATED',
  INITIATED: 'INITIATED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
}

