-- AUTO-GENERATED seed (249 rows) — scripts/build-geo-synonyms-seed-sql.mjs
INSERT INTO public.geo_synonyms (target_code, target_type, lang, alias_term, weight)
VALUES
  ('abu-dhabi', 'city', '*', 'abu-dhabi', 100),
  ('antalya', 'city', '*', 'antalya', 100),
  ('krabi-city', 'city', '*', 'ao nang', 95),
  ('krabi-city', 'city', '*', 'aonang', 95),
  ('Sukhumvit', 'district', '*', 'asok', 95),
  ('ID-BA', 'region', '*', 'bali', 100),
  ('Bang Tao', 'district', '*', 'bang tao', 95),
  ('bangkok', 'city', '*', 'bangkok', 100),
  ('Bang Tao', 'district', '*', 'bangtao', 95),
  ('bangkok', 'city', '*', 'bkk', 95),
  ('bodrum', 'city', '*', 'bodrum', 100),
  ('Panwa', 'district', '*', 'cape panwa', 98),
  ('Chalong', 'district', '*', 'chalong', 98),
  ('Cherngtalay', 'district', '*', 'cherng talay', 98),
  ('Cherngtalay', 'district', '*', 'cherngtalay', 95),
  ('chiang-mai', 'city', '*', 'chiang mai', 95),
  ('chiang-mai', 'city', '*', 'chiangmai', 95),
  ('dubai', 'city', '*', 'dubai', 100),
  ('Ekkamai', 'district', '*', 'ekkamai', 95),
  ('hua-hin', 'city', '*', 'hua hin', 95),
  ('hua-hin', 'city', '*', 'huahin', 95),
  ('istanbul', 'city', '*', 'istanbul', 100),
  ('pattaya', 'city', '*', 'jomtien', 95),
  ('Kamala', 'district', '*', 'kamala', 95),
  ('Khao San', 'district', '*', 'kaosan', 95),
  ('Karon', 'district', '*', 'karon', 95),
  ('Karon', 'district', '*', 'karon beach', 95),
  ('Kata', 'district', '*', 'kata', 95),
  ('Kata', 'district', '*', 'kata beach', 95),
  ('kazan', 'city', '*', 'kazan', 100),
  ('Khao San', 'district', '*', 'khao san', 95),
  ('samui', 'city', '*', 'ko samui', 95),
  ('samui', 'city', '*', 'koh samui', 95),
  ('krabi-city', 'city', '*', 'krabi', 100),
  ('bangkok', 'city', '*', 'krung', 95),
  ('bangkok', 'city', '*', 'krungthep', 95),
  ('Cherngtalay', 'district', '*', 'laguna', 95),
  ('Cherngtalay', 'district', '*', 'laguna phuket', 95),
  ('Mai Khao', 'district', '*', 'mai khao', 95),
  ('moscow', 'city', '*', 'moscow', 100),
  ('moscow', 'city', '*', 'msk', 100),
  ('Nai Harn', 'district', '*', 'nai harn', 95),
  ('Nai Yang', 'district', '*', 'nai yang', 95),
  ('Naklua', 'district', '*', 'naklua', 95),
  ('Sukhumvit', 'district', '*', 'nana', 95),
  ('Nimman', 'district', '*', 'nimman', 95),
  ('Nimman', 'district', '*', 'nimmanhaemin', 95),
  ('Old City', 'district', '*', 'old city', 95),
  ('Phuket Town', 'district', '*', 'old town', 95),
  ('Panwa', 'district', '*', 'panwa', 95),
  ('Patong', 'district', '*', 'patong', 98),
  ('Patong', 'district', '*', 'patong beach', 95),
  ('pattaya', 'city', '*', 'pattaya', 100),
  ('phang-nga', 'city', '*', 'phang nga', 95),
  ('phang-nga', 'city', '*', 'phangnga', 95),
  ('phuket-city', 'city', '*', 'phuket', 100),
  ('Phuket Town', 'district', '*', 'phuket town', 98),
  ('Pratunam', 'district', '*', 'pratunam', 95),
  ('Railay', 'district', '*', 'railay', 95),
  ('Railay', 'district', '*', 'railey', 95),
  ('Rawai', 'district', '*', 'rawai', 98),
  ('samara', 'city', '*', 'samara', 100),
  ('samui', 'city', '*', 'samui', 100),
  ('Sathorn', 'district', '*', 'sathorn', 95),
  ('Silom', 'district', '*', 'silom', 95),
  ('sochi', 'city', '*', 'sochi', 100),
  ('spb', 'city', '*', 'spb', 100),
  ('Sukhumvit', 'district', '*', 'sukhumvit', 95),
  ('Surin', 'district', '*', 'surin', 95),
  ('phuket-city', 'city', '*', 'thai', 95),
  ('phuket-city', 'city', '*', 'thailand', 95),
  ('Thalang', 'district', '*', 'thalang', 98),
  ('Thonglor', 'district', '*', 'thong lo', 95),
  ('Thonglor', 'district', '*', 'thonglor', 95),
  ('ubud', 'city', '*', 'ubud', 100),
  ('Chalong', 'district', 'en', 'Chalong', 100),
  ('kazan', 'city', 'en', 'kazan', 100),
  ('moscow', 'city', 'en', 'moscow', 100),
  ('Patong', 'district', 'en', 'Patong', 100),
  ('spb', 'city', 'en', 'petersburg', 100),
  ('spb', 'city', 'en', 'saint petersburg', 100),
  ('samara', 'city', 'en', 'samara', 100),
  ('sochi', 'city', 'en', 'sochi', 100),
  ('spb', 'city', 'en', 'st petersburg', 100),
  ('krabi-city', 'city', 'ru', 'ао нанг', 100),
  ('Sukhumvit', 'district', 'ru', 'асок', 100),
  ('Bang Tao', 'district', 'ru', 'банг тао', 100),
  ('bangkok', 'city', 'ru', 'бангкок', 100),
  ('Bang Tao', 'district', 'ru', 'бангтао', 100),
  ('bangkok', 'city', 'ru', 'бкк', 100),
  ('Phuket Town', 'district', 'ru', 'город', 100),
  ('pattaya', 'city', 'ru', 'джомтьен', 100),
  ('Jomtien', 'district', 'ru', 'джомтьен бич', 100),
  ('kazan', 'city', 'ru', 'казань', 100),
  ('Kamala', 'district', 'ru', 'камала', 100),
  ('Kamala', 'district', 'ru', 'камала бич', 100),
  ('Khao San', 'district', 'ru', 'каосан', 100),
  ('Karon', 'district', 'ru', 'карон', 100),
  ('Karon', 'district', 'ru', 'карон бич', 100),
  ('Kata', 'district', 'ru', 'ката', 100),
  ('Kata', 'district', 'ru', 'ката бич', 100),
  ('Panwa', 'district', 'ru', 'кейп панва', 100),
  ('samui', 'city', 'ru', 'ко самуи', 100),
  ('krabi-city', 'city', 'ru', 'краби', 100),
  ('Cherngtalay', 'district', 'ru', 'лагуна', 100),
  ('Mai Khao', 'district', 'ru', 'май кхао', 100),
  ('Mai Khao', 'district', 'ru', 'майкао', 100),
  ('moscow', 'city', 'ru', 'москва', 100),
  ('moscow', 'city', 'ru', 'мск', 100),
  ('Sukhumvit', 'district', 'ru', 'на на', 100),
  ('Nai Harn', 'district', 'ru', 'най харн', 100),
  ('Nai Yang', 'district', 'ru', 'най янг', 100),
  ('Nai Harn', 'district', 'ru', 'найхарн', 100),
  ('Naklua', 'district', 'ru', 'наклуа', 100),
  ('Nimman', 'district', 'ru', 'нимман', 100),
  ('phuket-city', 'city', 'ru', 'остров', 100),
  ('Panwa', 'district', 'ru', 'панва', 100),
  ('phang-nga', 'city', 'ru', 'пангнга', 100),
  ('Patong', 'district', 'ru', 'патонг', 100),
  ('Patong', 'district', 'ru', 'патонг бич', 100),
  ('pattaya', 'city', 'ru', 'паттайя', 100),
  ('pattaya', 'city', 'ru', 'паттая', 100),
  ('spb', 'city', 'ru', 'петербург', 100),
  ('spb', 'city', 'ru', 'питер', 100),
  ('Kata', 'district', 'ru', 'пляж ката', 100),
  ('Pratunam', 'district', 'ru', 'пратунам', 100),
  ('phuket-city', 'city', 'ru', 'пх', 100),
  ('phang-nga', 'city', 'ru', 'пхангнга', 100),
  ('phuket-city', 'city', 'ru', 'пхукет', 100),
  ('Phuket Town', 'district', 'ru', 'пхукет таун', 100),
  ('Rawai', 'district', 'ru', 'раваи', 100),
  ('Rawai', 'district', 'ru', 'равай', 100),
  ('Rawai', 'district', 'ru', 'район равай', 100),
  ('Railay', 'district', 'ru', 'рейли', 100),
  ('samara', 'city', 'ru', 'самара', 100),
  ('samui', 'city', 'ru', 'самуи', 100),
  ('spb', 'city', 'ru', 'санкт-петербург', 100),
  ('Sathorn', 'district', 'ru', 'сатхорн', 100),
  ('Silom', 'district', 'ru', 'силом', 100),
  ('sochi', 'city', 'ru', 'сочи', 100),
  ('spb', 'city', 'ru', 'спб', 100),
  ('Phuket Town', 'district', 'ru', 'старый город', 100),
  ('Sukhumvit', 'district', 'ru', 'сукхумвит', 100),
  ('Surin', 'district', 'ru', 'сурин', 100),
  ('Surin', 'district', 'ru', 'сурин бич', 100),
  ('phuket-city', 'city', 'ru', 'таиланд', 100),
  ('Thonglor', 'district', 'ru', 'тонглор', 100),
  ('Thalang', 'district', 'ru', 'тхаланг', 100),
  ('hua-hin', 'city', 'ru', 'хуа хин', 100),
  ('hua-hin', 'city', 'ru', 'хуахин', 100),
  ('Chalong', 'district', 'ru', 'чалон', 100),
  ('Chalong', 'district', 'ru', 'чалонг', 100),
  ('Cherngtalay', 'district', 'ru', 'чернгталай', 100),
  ('chiang-mai', 'city', 'ru', 'чианг май', 100),
  ('chiang-mai', 'city', 'ru', 'чиангмай', 100),
  ('Ekkamai', 'district', 'ru', 'эккамай', 100),
  ('bangkok', 'city', 'th', 'กทม', 100),
  ('Kamala', 'district', 'th', 'กมลา', 100),
  ('krabi-city', 'city', 'th', 'กระบี่', 100),
  ('bangkok', 'city', 'th', 'กรุงเทพ', 100),
  ('Kata', 'district', 'th', 'กะตะ', 100),
  ('Karon', 'district', 'th', 'กะรน', 100),
  ('samui', 'city', 'th', 'เกาะสมุย', 100),
  ('Khao San', 'district', 'th', 'ข้าวสาร', 100),
  ('Jomtien', 'district', 'th', 'จอมเทียน', 100),
  ('Chalong', 'district', 'th', 'ฉลอง', 100),
  ('Cherngtalay', 'district', 'th', 'เชิงทะเล', 100),
  ('chiang-mai', 'city', 'th', 'เชียงใหม่', 100),
  ('Thalang', 'district', 'th', 'ถลาง', 100),
  ('Thonglor', 'district', 'th', 'ทองหล่อ', 100),
  ('Naklua', 'district', 'th', 'นาเกลือ', 100),
  ('Nimman', 'district', 'th', 'นิมมาน', 100),
  ('Old City', 'district', 'th', 'ในเมือง', 100),
  ('Nai Yang', 'district', 'th', 'ในยาง', 100),
  ('Nai Harn', 'district', 'th', 'ในหาน', 100),
  ('Bang Tao', 'district', 'th', 'บางเทา', 100),
  ('Pratunam', 'district', 'th', 'ประตูน้ำ', 100),
  ('phuket-city', 'city', 'th', 'ประเทศไทย', 100),
  ('Patong', 'district', 'th', 'ป่าตอง', 100),
  ('phang-nga', 'city', 'th', 'พังงา', 100),
  ('pattaya', 'city', 'th', 'พัทยา', 100),
  ('Panwa', 'district', 'th', 'พันวา', 100),
  ('phuket-city', 'city', 'th', 'ภูเก็ต', 100),
  ('Phuket Town', 'district', 'th', 'เมืองเก่า', 100),
  ('Phuket Town', 'district', 'th', 'เมืองภูเก็ต', 100),
  ('Mai Khao', 'district', 'th', 'ไม้ขาว', 100),
  ('Rawai', 'district', 'th', 'ราไวย์', 100),
  ('Railay', 'district', 'th', 'ไร่เลย์', 100),
  ('samui', 'city', 'th', 'สมุย', 100),
  ('Sathorn', 'district', 'th', 'สาทร', 100),
  ('Silom', 'district', 'th', 'สีลม', 100),
  ('Sukhumvit', 'district', 'th', 'สุขุมวิท', 100),
  ('Surin', 'district', 'th', 'สุรินทร์', 100),
  ('hua-hin', 'city', 'th', 'หัวหิน', 100),
  ('Kamala', 'district', 'th', 'หาดกมลา', 100),
  ('Kata', 'district', 'th', 'หาดกะตะ', 100),
  ('Karon', 'district', 'th', 'หาดกะรน', 100),
  ('Jomtien', 'district', 'th', 'หาดจอมเทียน', 100),
  ('Nai Yang', 'district', 'th', 'หาดในยาง', 100),
  ('Nai Harn', 'district', 'th', 'หาดในหาน', 100),
  ('Bang Tao', 'district', 'th', 'หาดบางเทา', 100),
  ('Patong', 'district', 'th', 'หาดป่าตอง', 100),
  ('Mai Khao', 'district', 'th', 'หาดไม้ขาว', 100),
  ('Surin', 'district', 'th', 'หาดสุรินทร์', 100),
  ('Panwa', 'district', 'th', 'แหลมพันวา', 100),
  ('krabi-city', 'city', 'th', 'อ่าวนาง', 100),
  ('Ekkamai', 'district', 'th', 'เอกมัย', 100),
  ('Jomtien', 'district', 'zh', '中天', 100),
  ('Ekkamai', 'district', 'zh', '亿甲迈', 100),
  ('Thalang', 'district', 'zh', '他朗', 100),
  ('hua-hin', 'city', 'zh', '华欣', 100),
  ('Karon', 'district', 'zh', '卡伦', 100),
  ('Kata', 'district', 'zh', '卡塔', 100),
  ('Kamala', 'district', 'zh', '卡马拉', 100),
  ('Old City', 'district', 'zh', '古城', 100),
  ('Nai Yang', 'district', 'zh', '奈扬', 100),
  ('Nai Harn', 'district', 'zh', '奈汉', 100),
  ('krabi-city', 'city', 'zh', '奥南', 100),
  ('Nimman', 'district', 'zh', '宁曼', 100),
  ('Cherngtalay', 'district', 'zh', '承塔莱', 100),
  ('Rawai', 'district', 'zh', '拉威', 100),
  ('phang-nga', 'city', 'zh', '攀牙', 100),
  ('Panwa', 'district', 'zh', '攀瓦', 100),
  ('Cape Panwa', 'district', 'zh', '攀瓦角', 100),
  ('Silom', 'district', 'zh', '是隆', 100),
  ('phuket-city', 'city', 'zh', '普吉', 100),
  ('phuket-city', 'city', 'zh', '普吉岛', 100),
  ('Phuket Town', 'district', 'zh', '普吉镇', 100),
  ('bangkok', 'city', 'zh', '曼谷', 100),
  ('Chalong', 'district', 'zh', '查龙', 100),
  ('Pratunam', 'district', 'zh', '水门', 100),
  ('Sathorn', 'district', 'zh', '沙吞', 100),
  ('phuket-city', 'city', 'zh', '泰国', 100),
  ('chiang-mai', 'city', 'zh', '清迈', 100),
  ('krabi-city', 'city', 'zh', '甲米', 100),
  ('Sukhumvit', 'district', 'zh', '素坤逸', 100),
  ('Phuket Town', 'district', 'zh', '老城', 100),
  ('Khao San', 'district', 'zh', '考山路', 100),
  ('Patong', 'district', 'zh', '芭东', 100),
  ('pattaya', 'city', 'zh', '芭堤雅', 100),
  ('pattaya', 'city', 'zh', '芭提雅', 100),
  ('Surin', 'district', 'zh', '苏林', 100),
  ('samui', 'city', 'zh', '苏梅', 100),
  ('samui', 'city', 'zh', '苏梅岛', 100),
  ('Railay', 'district', 'zh', '莱利', 100),
  ('Mai Khao', 'district', 'zh', '迈考', 100),
  ('Thonglor', 'district', 'zh', '通罗', 100),
  ('Naklua', 'district', 'zh', '那库阿', 100),
  ('Bang Tao', 'district', 'zh', '邦涛', 100)
ON CONFLICT (lower(alias_term), lang) DO NOTHING;
