-- Stage 158.3 — geo_synonyms registry (multilingual location aliases for suggest).
-- Seed: scripts/build-geo-synonyms-seed-sql.mjs → stage158_3_geo_synonyms_seed.generated.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public.geo_synonyms (
  id            TEXT PRIMARY KEY DEFAULT ('gsyn-' || gen_random_uuid()::text),
  target_code   TEXT NOT NULL,
  target_type   TEXT NOT NULL
                CHECK (target_type IN ('country', 'region', 'city', 'district')),
  lang          TEXT NOT NULL
                CHECK (lang IN ('ru', 'en', 'th', 'zh', '*')),
  alias_term    TEXT NOT NULL,
  weight        SMALLINT NOT NULL DEFAULT 100,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.geo_synonyms IS
  'Stage 158.3 — multilingual alias → canonical geo code for location suggest.';
COMMENT ON COLUMN public.geo_synonyms.lang IS
  'ru|en|th|zh = locale-specific spelling; * = language-neutral (latin slugs, bkk, phuket).';

CREATE UNIQUE INDEX IF NOT EXISTS uniq_geo_synonyms_alias_lang
  ON public.geo_synonyms (lower(alias_term), lang);

CREATE INDEX IF NOT EXISTS idx_geo_synonyms_target
  ON public.geo_synonyms (target_type, target_code);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.geo_synonyms TO service_role;

ALTER TABLE public.geo_synonyms ENABLE ROW LEVEL SECURITY;

COMMIT;

-- AUTO-GENERATED seed (249 rows) вЂ” scripts/build-geo-synonyms-seed-sql.mjs
INSERT INTO public.geo_synonyms (target_code, target_type, lang, alias_term, weight)
VALUES
  ('abu-dhabi', 'city', '*', 'abu-dhabi', 100),
  ('antalya', 'city', '*', 'antalya', 100),
  ('krabi-city', 'city', '*', 'ao nang', 95),
  ('krabi-city', 'city', '*', 'aonang', 95),
  ('Sukhumvit', 'district', '*', 'asok', 95),
  ('ID-BA', 'region', '*', 'bali', 100),
  ('Bang Tao', 'district', '*', 'bang tao', 95),
  ('bangkok', 'city', '*', 'bangkok', 100),
  ('Bang Tao', 'district', '*', 'bangtao', 95),
  ('bangkok', 'city', '*', 'bkk', 95),
  ('bodrum', 'city', '*', 'bodrum', 100),
  ('Panwa', 'district', '*', 'cape panwa', 98),
  ('Chalong', 'district', '*', 'chalong', 98),
  ('Cherngtalay', 'district', '*', 'cherng talay', 98),
  ('Cherngtalay', 'district', '*', 'cherngtalay', 95),
  ('chiang-mai', 'city', '*', 'chiang mai', 95),
  ('chiang-mai', 'city', '*', 'chiangmai', 95),
  ('dubai', 'city', '*', 'dubai', 100),
  ('Ekkamai', 'district', '*', 'ekkamai', 95),
  ('hua-hin', 'city', '*', 'hua hin', 95),
  ('hua-hin', 'city', '*', 'huahin', 95),
  ('istanbul', 'city', '*', 'istanbul', 100),
  ('pattaya', 'city', '*', 'jomtien', 95),
  ('Kamala', 'district', '*', 'kamala', 95),
  ('Khao San', 'district', '*', 'kaosan', 95),
  ('Karon', 'district', '*', 'karon', 95),
  ('Karon', 'district', '*', 'karon beach', 95),
  ('Kata', 'district', '*', 'kata', 95),
  ('Kata', 'district', '*', 'kata beach', 95),
  ('kazan', 'city', '*', 'kazan', 100),
  ('Khao San', 'district', '*', 'khao san', 95),
  ('samui', 'city', '*', 'ko samui', 95),
  ('samui', 'city', '*', 'koh samui', 95),
  ('krabi-city', 'city', '*', 'krabi', 100),
  ('bangkok', 'city', '*', 'krung', 95),
  ('bangkok', 'city', '*', 'krungthep', 95),
  ('Cherngtalay', 'district', '*', 'laguna', 95),
  ('Cherngtalay', 'district', '*', 'laguna phuket', 95),
  ('Mai Khao', 'district', '*', 'mai khao', 95),
  ('moscow', 'city', '*', 'moscow', 100),
  ('moscow', 'city', '*', 'msk', 100),
  ('Nai Harn', 'district', '*', 'nai harn', 95),
  ('Nai Yang', 'district', '*', 'nai yang', 95),
  ('Naklua', 'district', '*', 'naklua', 95),
  ('Sukhumvit', 'district', '*', 'nana', 95),
  ('Nimman', 'district', '*', 'nimman', 95),
  ('Nimman', 'district', '*', 'nimmanhaemin', 95),
  ('Old City', 'district', '*', 'old city', 95),
  ('Phuket Town', 'district', '*', 'old town', 95),
  ('Panwa', 'district', '*', 'panwa', 95),
  ('Patong', 'district', '*', 'patong', 98),
  ('Patong', 'district', '*', 'patong beach', 95),
  ('pattaya', 'city', '*', 'pattaya', 100),
  ('phang-nga', 'city', '*', 'phang nga', 95),
  ('phang-nga', 'city', '*', 'phangnga', 95),
  ('phuket-city', 'city', '*', 'phuket', 100),
  ('Phuket Town', 'district', '*', 'phuket town', 98),
  ('Pratunam', 'district', '*', 'pratunam', 95),
  ('Railay', 'district', '*', 'railay', 95),
  ('Railay', 'district', '*', 'railey', 95),
  ('Rawai', 'district', '*', 'rawai', 98),
  ('samara', 'city', '*', 'samara', 100),
  ('samui', 'city', '*', 'samui', 100),
  ('Sathorn', 'district', '*', 'sathorn', 95),
  ('Silom', 'district', '*', 'silom', 95),
  ('sochi', 'city', '*', 'sochi', 100),
  ('spb', 'city', '*', 'spb', 100),
  ('Sukhumvit', 'district', '*', 'sukhumvit', 95),
  ('Surin', 'district', '*', 'surin', 95),
  ('phuket-city', 'city', '*', 'thai', 95),
  ('phuket-city', 'city', '*', 'thailand', 95),
  ('Thalang', 'district', '*', 'thalang', 98),
  ('Thonglor', 'district', '*', 'thong lo', 95),
  ('Thonglor', 'district', '*', 'thonglor', 95),
  ('ubud', 'city', '*', 'ubud', 100),
  ('Chalong', 'district', 'en', 'Chalong', 100),
  ('kazan', 'city', 'en', 'kazan', 100),
  ('moscow', 'city', 'en', 'moscow', 100),
  ('Patong', 'district', 'en', 'Patong', 100),
  ('spb', 'city', 'en', 'petersburg', 100),
  ('spb', 'city', 'en', 'saint petersburg', 100),
  ('samara', 'city', 'en', 'samara', 100),
  ('sochi', 'city', 'en', 'sochi', 100),
  ('spb', 'city', 'en', 'st petersburg', 100),
  ('krabi-city', 'city', 'ru', 'Р°Рѕ РЅР°РЅРі', 100),
  ('Sukhumvit', 'district', 'ru', 'Р°СЃРѕРє', 100),
  ('Bang Tao', 'district', 'ru', 'Р±Р°РЅРі С‚Р°Рѕ', 100),
  ('bangkok', 'city', 'ru', 'Р±Р°РЅРіРєРѕРє', 100),
  ('Bang Tao', 'district', 'ru', 'Р±Р°РЅРіС‚Р°Рѕ', 100),
  ('bangkok', 'city', 'ru', 'Р±РєРє', 100),
  ('Phuket Town', 'district', 'ru', 'РіРѕСЂРѕРґ', 100),
  ('pattaya', 'city', 'ru', 'РґР¶РѕРјС‚СЊРµРЅ', 100),
  ('Jomtien', 'district', 'ru', 'РґР¶РѕРјС‚СЊРµРЅ Р±РёС‡', 100),
  ('kazan', 'city', 'ru', 'РєР°Р·Р°РЅСЊ', 100),
  ('Kamala', 'district', 'ru', 'РєР°РјР°Р»Р°', 100),
  ('Kamala', 'district', 'ru', 'РєР°РјР°Р»Р° Р±РёС‡', 100),
  ('Khao San', 'district', 'ru', 'РєР°РѕСЃР°РЅ', 100),
  ('Karon', 'district', 'ru', 'РєР°СЂРѕРЅ', 100),
  ('Karon', 'district', 'ru', 'РєР°СЂРѕРЅ Р±РёС‡', 100),
  ('Kata', 'district', 'ru', 'РєР°С‚Р°', 100),
  ('Kata', 'district', 'ru', 'РєР°С‚Р° Р±РёС‡', 100),
  ('Panwa', 'district', 'ru', 'РєРµР№Рї РїР°РЅРІР°', 100),
  ('samui', 'city', 'ru', 'РєРѕ СЃР°РјСѓРё', 100),
  ('krabi-city', 'city', 'ru', 'РєСЂР°Р±Рё', 100),
  ('Cherngtalay', 'district', 'ru', 'Р»Р°РіСѓРЅР°', 100),
  ('Mai Khao', 'district', 'ru', 'РјР°Р№ РєС…Р°Рѕ', 100),
  ('Mai Khao', 'district', 'ru', 'РјР°Р№РєР°Рѕ', 100),
  ('moscow', 'city', 'ru', 'РјРѕСЃРєРІР°', 100),
  ('moscow', 'city', 'ru', 'РјСЃРє', 100),
  ('Sukhumvit', 'district', 'ru', 'РЅР° РЅР°', 100),
  ('Nai Harn', 'district', 'ru', 'РЅР°Р№ С…Р°СЂРЅ', 100),
  ('Nai Yang', 'district', 'ru', 'РЅР°Р№ СЏРЅРі', 100),
  ('Nai Harn', 'district', 'ru', 'РЅР°Р№С…Р°СЂРЅ', 100),
  ('Naklua', 'district', 'ru', 'РЅР°РєР»СѓР°', 100),
  ('Nimman', 'district', 'ru', 'РЅРёРјРјР°РЅ', 100),
  ('phuket-city', 'city', 'ru', 'РѕСЃС‚СЂРѕРІ', 100),
  ('Panwa', 'district', 'ru', 'РїР°РЅРІР°', 100),
  ('phang-nga', 'city', 'ru', 'РїР°РЅРіРЅРіР°', 100),
  ('Patong', 'district', 'ru', 'РїР°С‚РѕРЅРі', 100),
  ('Patong', 'district', 'ru', 'РїР°С‚РѕРЅРі Р±РёС‡', 100),
  ('pattaya', 'city', 'ru', 'РїР°С‚С‚Р°Р№СЏ', 100),
  ('pattaya', 'city', 'ru', 'РїР°С‚С‚Р°СЏ', 100),
  ('spb', 'city', 'ru', 'РїРµС‚РµСЂР±СѓСЂРі', 100),
  ('spb', 'city', 'ru', 'РїРёС‚РµСЂ', 100),
  ('Kata', 'district', 'ru', 'РїР»СЏР¶ РєР°С‚Р°', 100),
  ('Pratunam', 'district', 'ru', 'РїСЂР°С‚СѓРЅР°Рј', 100),
  ('phuket-city', 'city', 'ru', 'РїС…', 100),
  ('phang-nga', 'city', 'ru', 'РїС…Р°РЅРіРЅРіР°', 100),
  ('phuket-city', 'city', 'ru', 'РїС…СѓРєРµС‚', 100),
  ('Phuket Town', 'district', 'ru', 'РїС…СѓРєРµС‚ С‚Р°СѓРЅ', 100),
  ('Rawai', 'district', 'ru', 'СЂР°РІР°Рё', 100),
  ('Rawai', 'district', 'ru', 'СЂР°РІР°Р№', 100),
  ('Rawai', 'district', 'ru', 'СЂР°Р№РѕРЅ СЂР°РІР°Р№', 100),
  ('Railay', 'district', 'ru', 'СЂРµР№Р»Рё', 100),
  ('samara', 'city', 'ru', 'СЃР°РјР°СЂР°', 100),
  ('samui', 'city', 'ru', 'СЃР°РјСѓРё', 100),
  ('spb', 'city', 'ru', 'СЃР°РЅРєС‚-РїРµС‚РµСЂР±СѓСЂРі', 100),
  ('Sathorn', 'district', 'ru', 'СЃР°С‚С…РѕСЂРЅ', 100),
  ('Silom', 'district', 'ru', 'СЃРёР»РѕРј', 100),
  ('sochi', 'city', 'ru', 'СЃРѕС‡Рё', 100),
  ('spb', 'city', 'ru', 'СЃРїР±', 100),
  ('Phuket Town', 'district', 'ru', 'СЃС‚Р°СЂС‹Р№ РіРѕСЂРѕРґ', 100),
  ('Sukhumvit', 'district', 'ru', 'СЃСѓРєС…СѓРјРІРёС‚', 100),
  ('Surin', 'district', 'ru', 'СЃСѓСЂРёРЅ', 100),
  ('Surin', 'district', 'ru', 'СЃСѓСЂРёРЅ Р±РёС‡', 100),
  ('phuket-city', 'city', 'ru', 'С‚Р°РёР»Р°РЅРґ', 100),
  ('Thonglor', 'district', 'ru', 'С‚РѕРЅРіР»РѕСЂ', 100),
  ('Thalang', 'district', 'ru', 'С‚С…Р°Р»Р°РЅРі', 100),
  ('hua-hin', 'city', 'ru', 'С…СѓР° С…РёРЅ', 100),
  ('hua-hin', 'city', 'ru', 'С…СѓР°С…РёРЅ', 100),
  ('Chalong', 'district', 'ru', 'С‡Р°Р»РѕРЅ', 100),
  ('Chalong', 'district', 'ru', 'С‡Р°Р»РѕРЅРі', 100),
  ('Cherngtalay', 'district', 'ru', 'С‡РµСЂРЅРіС‚Р°Р»Р°Р№', 100),
  ('chiang-mai', 'city', 'ru', 'С‡РёР°РЅРі РјР°Р№', 100),
  ('chiang-mai', 'city', 'ru', 'С‡РёР°РЅРіРјР°Р№', 100),
  ('Ekkamai', 'district', 'ru', 'СЌРєРєР°РјР°Р№', 100),
  ('bangkok', 'city', 'th', 'аёЃаё—аёЎ', 100),
  ('Kamala', 'district', 'th', 'аёЃаёЎаёҐаёІ', 100),
  ('krabi-city', 'city', 'th', 'аёЃаёЈаё°аёљаёµа№€', 100),
  ('bangkok', 'city', 'th', 'аёЃаёЈаёёаё‡а№Ђаё—аёћ', 100),
  ('Kata', 'district', 'th', 'аёЃаё°аё•аё°', 100),
  ('Karon', 'district', 'th', 'аёЃаё°аёЈаё™', 100),
  ('samui', 'city', 'th', 'а№ЂаёЃаёІаё°аёЄаёЎаёёаёў', 100),
  ('Khao San', 'district', 'th', 'аё‚а№‰аёІаё§аёЄаёІаёЈ', 100),
  ('Jomtien', 'district', 'th', 'аё€аё­аёЎа№Ђаё—аёµаёўаё™', 100),
  ('Chalong', 'district', 'th', 'аё‰аёҐаё­аё‡', 100),
  ('Cherngtalay', 'district', 'th', 'а№ЂаёЉаёґаё‡аё—аё°а№ЂаёҐ', 100),
  ('chiang-mai', 'city', 'th', 'а№ЂаёЉаёµаёўаё‡а№ѓаё«аёЎа№€', 100),
  ('Thalang', 'district', 'th', 'аё–аёҐаёІаё‡', 100),
  ('Thonglor', 'district', 'th', 'аё—аё­аё‡аё«аёҐа№€аё­', 100),
  ('Naklua', 'district', 'th', 'аё™аёІа№ЂаёЃаёҐаё·аё­', 100),
  ('Nimman', 'district', 'th', 'аё™аёґаёЎаёЎаёІаё™', 100),
  ('Old City', 'district', 'th', 'а№ѓаё™а№ЂаёЎаё·аё­аё‡', 100),
  ('Nai Yang', 'district', 'th', 'а№ѓаё™аёўаёІаё‡', 100),
  ('Nai Harn', 'district', 'th', 'а№ѓаё™аё«аёІаё™', 100),
  ('Bang Tao', 'district', 'th', 'аёљаёІаё‡а№Ђаё—аёІ', 100),
  ('Pratunam', 'district', 'th', 'аё›аёЈаё°аё•аё№аё™а№‰аёі', 100),
  ('phuket-city', 'city', 'th', 'аё›аёЈаё°а№Ђаё—аёЁа№„аё—аёў', 100),
  ('Patong', 'district', 'th', 'аё›а№€аёІаё•аё­аё‡', 100),
  ('phang-nga', 'city', 'th', 'аёћаё±аё‡аё‡аёІ', 100),
  ('pattaya', 'city', 'th', 'аёћаё±аё—аёўаёІ', 100),
  ('Panwa', 'district', 'th', 'аёћаё±аё™аё§аёІ', 100),
  ('phuket-city', 'city', 'th', 'аё аё№а№ЂаёЃа№‡аё•', 100),
  ('Phuket Town', 'district', 'th', 'а№ЂаёЎаё·аё­аё‡а№ЂаёЃа№€аёІ', 100),
  ('Phuket Town', 'district', 'th', 'а№ЂаёЎаё·аё­аё‡аё аё№а№ЂаёЃа№‡аё•', 100),
  ('Mai Khao', 'district', 'th', 'а№„аёЎа№‰аё‚аёІаё§', 100),
  ('Rawai', 'district', 'th', 'аёЈаёІа№„аё§аёўа№Њ', 100),
  ('Railay', 'district', 'th', 'а№„аёЈа№€а№ЂаёҐаёўа№Њ', 100),
  ('samui', 'city', 'th', 'аёЄаёЎаёёаёў', 100),
  ('Sathorn', 'district', 'th', 'аёЄаёІаё—аёЈ', 100),
  ('Silom', 'district', 'th', 'аёЄаёµаёҐаёЎ', 100),
  ('Sukhumvit', 'district', 'th', 'аёЄаёёаё‚аёёаёЎаё§аёґаё—', 100),
  ('Surin', 'district', 'th', 'аёЄаёёаёЈаёґаё™аё—аёЈа№Њ', 100),
  ('hua-hin', 'city', 'th', 'аё«аё±аё§аё«аёґаё™', 100),
  ('Kamala', 'district', 'th', 'аё«аёІаё”аёЃаёЎаёҐаёІ', 100),
  ('Kata', 'district', 'th', 'аё«аёІаё”аёЃаё°аё•аё°', 100),
  ('Karon', 'district', 'th', 'аё«аёІаё”аёЃаё°аёЈаё™', 100),
  ('Jomtien', 'district', 'th', 'аё«аёІаё”аё€аё­аёЎа№Ђаё—аёµаёўаё™', 100),
  ('Nai Yang', 'district', 'th', 'аё«аёІаё”а№ѓаё™аёўаёІаё‡', 100),
  ('Nai Harn', 'district', 'th', 'аё«аёІаё”а№ѓаё™аё«аёІаё™', 100),
  ('Bang Tao', 'district', 'th', 'аё«аёІаё”аёљаёІаё‡а№Ђаё—аёІ', 100),
  ('Patong', 'district', 'th', 'аё«аёІаё”аё›а№€аёІаё•аё­аё‡', 100),
  ('Mai Khao', 'district', 'th', 'аё«аёІаё”а№„аёЎа№‰аё‚аёІаё§', 100),
  ('Surin', 'district', 'th', 'аё«аёІаё”аёЄаёёаёЈаёґаё™аё—аёЈа№Њ', 100),
  ('Panwa', 'district', 'th', 'а№Ѓаё«аёҐаёЎаёћаё±аё™аё§аёІ', 100),
  ('krabi-city', 'city', 'th', 'аё­а№€аёІаё§аё™аёІаё‡', 100),
  ('Ekkamai', 'district', 'th', 'а№Ђаё­аёЃаёЎаё±аёў', 100),
  ('Jomtien', 'district', 'zh', 'дё­е¤©', 100),
  ('Ekkamai', 'district', 'zh', 'дєїз”Іиї€', 100),
  ('Thalang', 'district', 'zh', 'д»–жњ—', 100),
  ('hua-hin', 'city', 'zh', 'еЌЋж¬Ј', 100),
  ('Karon', 'district', 'zh', 'еЌЎдј¦', 100),
  ('Kata', 'district', 'zh', 'еЌЎеЎ”', 100),
  ('Kamala', 'district', 'zh', 'еЌЎй©¬ж‹‰', 100),
  ('Old City', 'district', 'zh', 'еЏ¤еџЋ', 100),
  ('Nai Yang', 'district', 'zh', 'еҐ€ж‰¬', 100),
  ('Nai Harn', 'district', 'zh', 'еҐ€ж±‰', 100),
  ('krabi-city', 'city', 'zh', 'еҐҐеЌ—', 100),
  ('Nimman', 'district', 'zh', 'е®Ѓж›ј', 100),
  ('Cherngtalay', 'district', 'zh', 'ж‰їеЎ”иЋ±', 100),
  ('Rawai', 'district', 'zh', 'ж‹‰еЁЃ', 100),
  ('phang-nga', 'city', 'zh', 'ж”Ђз‰™', 100),
  ('Panwa', 'district', 'zh', 'ж”Ђз“¦', 100),
  ('Cape Panwa', 'district', 'zh', 'ж”Ђз“¦и§’', 100),
  ('Silom', 'district', 'zh', 'жЇйљ†', 100),
  ('phuket-city', 'city', 'zh', 'ж™®еђ‰', 100),
  ('phuket-city', 'city', 'zh', 'ж™®еђ‰еІ›', 100),
  ('Phuket Town', 'district', 'zh', 'ж™®еђ‰й•‡', 100),
  ('bangkok', 'city', 'zh', 'ж›ји°·', 100),
  ('Chalong', 'district', 'zh', 'жџҐйѕ™', 100),
  ('Pratunam', 'district', 'zh', 'ж°ґй—Ё', 100),
  ('Sathorn', 'district', 'zh', 'жІ™еђћ', 100),
  ('phuket-city', 'city', 'zh', 'жі°е›Ѕ', 100),
  ('chiang-mai', 'city', 'zh', 'жё…иї€', 100),
  ('krabi-city', 'city', 'zh', 'з”Із±і', 100),
  ('Sukhumvit', 'district', 'zh', 'зґ еќ¤йЂё', 100),
  ('Phuket Town', 'district', 'zh', 'иЂЃеџЋ', 100),
  ('Khao San', 'district', 'zh', 'иЂѓе±±и·Ї', 100),
  ('Patong', 'district', 'zh', 'иЉ­дёњ', 100),
  ('pattaya', 'city', 'zh', 'иЉ­е ¤й›…', 100),
  ('pattaya', 'city', 'zh', 'иЉ­жЏђй›…', 100),
  ('Surin', 'district', 'zh', 'и‹Џжћ—', 100),
  ('samui', 'city', 'zh', 'и‹Џжў…', 100),
  ('samui', 'city', 'zh', 'и‹Џжў…еІ›', 100),
  ('Railay', 'district', 'zh', 'иЋ±е€©', 100),
  ('Mai Khao', 'district', 'zh', 'иї€иЂѓ', 100),
  ('Thonglor', 'district', 'zh', 'йЂљзЅ—', 100),
  ('Naklua', 'district', 'zh', 'й‚Јеє“йї', 100),
  ('Bang Tao', 'district', 'zh', 'й‚¦ж¶›', 100)
ON CONFLICT (lower(alias_term), lang) DO NOTHING;
