/**
 * Таиланд — мультиязычные подписи и строки для поиска (RU / EN / ZH / TH).
 * Ключ = каноническое значение из API (?where=, metadata.city, district).
 */

/** @typedef {{ ru: string, en: string, zh: string, th: string, match: string[] }} LocationMeta */

/** @type {Record<string, LocationMeta>} */
export const CITY_ALIASES = {
  Phuket: {
    ru: 'Пхукет, Таиланд',
    en: 'Phuket, Thailand',
    zh: '普吉岛，泰国',
    th: 'ภูเก็ต, ประเทศไทย',
    match: [
      'phuket',
      'пхукет',
      'пх',
      'таиланд',
      'thailand',
      'thai',
      'остров',
      '普吉',
      '普吉岛',
      '泰国',
      'ภูเก็ต',
      'ประเทศไทย',
    ],
  },
  Bangkok: {
    ru: 'Бангкок, Таиланд',
    en: 'Bangkok, Thailand',
    zh: '曼谷，泰国',
    th: 'กรุงเทพฯ, ประเทศไทย',
    match: [
      'bangkok',
      'бангкок',
      'бкк',
      'bkk',
      'krung',
      'krungthep',
      '曼谷',
      '泰国',
      'กรุงเทพ',
      'กทม',
    ],
  },
  'Chiang Mai': {
    ru: 'Чиангмай, Таиланд',
    en: 'Chiang Mai, Thailand',
    zh: '清迈，泰国',
    th: 'เชียงใหม่, ประเทศไทย',
    match: [
      'chiang mai',
      'chiangmai',
      'чиангмай',
      'чианг май',
      '清迈',
      '泰国',
      'เชียงใหม่',
    ],
  },
  Pattaya: {
    ru: 'Паттайя, Таиланд',
    en: 'Pattaya, Thailand',
    zh: '芭堤雅，泰国',
    th: 'พัทยา, ประเทศไทย',
    match: [
      'pattaya',
      'паттайя',
      'паттая',
      'jomtien',
      'джомтьен',
      '芭堤雅',
      '芭提雅',
      '泰国',
      'พัทยา',
    ],
  },
  Krabi: {
    ru: 'Краби, Таиланд',
    en: 'Krabi, Thailand',
    zh: '甲米，泰国',
    th: 'กระบี่, ประเทศไทย',
    match: [
      'krabi',
      'краби',
      'aonang',
      'ao nang',
      'ао нанг',
      '甲米',
      '奥南',
      '泰国',
      'กระบี่',
      'อ่าวนาง',
    ],
  },
  'Koh Samui': {
    ru: 'Самуи, Таиланд',
    en: 'Koh Samui, Thailand',
    zh: '苏梅岛，泰国',
    th: 'เกาะสมุย, ประเทศไทย',
    match: [
      'samui',
      'koh samui',
      'ko samui',
      'самуи',
      'ко самуи',
      '苏梅',
      '苏梅岛',
      '泰国',
      'สมุย',
      'เกาะสมุย',
    ],
  },
  Samui: {
    ru: 'Самуи, Таиланд',
    en: 'Samui, Thailand',
    zh: '苏梅岛，泰国',
    th: 'เกาะสมุย, ประเทศไทย',
    match: [
      'samui',
      'самуи',
      '苏梅',
      '苏梅岛',
      'สมุย',
      'เกาะสมุย',
    ],
  },
  'Hua Hin': {
    ru: 'Хуа Хин, Таиланд',
    en: 'Hua Hin, Thailand',
    zh: '华欣，泰国',
    th: 'หัวหิน, ประเทศไทย',
    match: [
      'hua hin',
      'huahin',
      'хуа хин',
      'хуахин',
      '华欣',
      '泰国',
      'หัวหิน',
    ],
  },
  'Phang Nga': {
    ru: 'Пхангнга, Таиланд',
    en: 'Phang Nga, Thailand',
    zh: '攀牙，泰国',
    th: 'พังงา, ประเทศไทย',
    match: [
      'phang nga',
      'phangnga',
      'пхангнга',
      'пангнга',
      '攀牙',
      '泰国',
      'พังงา',
    ],
  },
  Other: {
    ru: 'Другое',
    en: 'Other',
    zh: '其他',
    th: 'อื่น ๆ',
    match: ['other', 'другое', 'прочее', '其他', 'อื่น'],
  },
}

/** District (DB) → labels + варианты ввода */
/** @type {Record<string, LocationMeta>} */
export const DISTRICT_ALIASES = {
  // —— Пхукет ——
  Rawai: {
    ru: 'Равай, Пхукет',
    en: 'Rawai, Phuket',
    zh: '拉威，普吉',
    th: 'ราไวย์, ภูเก็ต',
    match: ['rawai', 'равай', 'раваи', 'район равай', '拉威', 'ราไวย์'],
  },
  Chalong: {
    ru: 'Чалонг, Пхукет',
    en: 'Chalong, Phuket',
    zh: '查龙，普吉',
    th: 'ฉลอง, ภูเก็ต',
    match: ['chalong', 'чалонг', 'чалон', '查龙', 'ฉลอง'],
  },
  Kata: {
    ru: 'Ката / Пляж Ката, Пхукет',
    en: 'Kata Beach, Phuket',
    zh: '卡塔海滩，普吉',
    th: 'หาดกะตะ, ภูเก็ต',
    match: ['kata', 'ката', 'ката бич', 'kata beach', 'пляж ката', '卡塔', 'กะตะ', 'หาดกะตะ'],
  },
  Karon: {
    ru: 'Карон, Пхукет',
    en: 'Karon, Phuket',
    zh: '卡伦，普吉',
    th: 'หาดกะรน, ภูเก็ต',
    match: ['karon', 'карон', 'карон бич', 'karon beach', '卡伦', 'กะรน', 'หาดกะรน'],
  },
  Patong: {
    ru: 'Патонг, Пхукет',
    en: 'Patong, Phuket',
    zh: '芭东，普吉',
    th: 'ป่าตอง, ภูเก็ต',
    match: ['patong', 'патонг', 'патонг бич', 'patong beach', '芭东', 'ป่าตอง', 'หาดป่าตอง'],
  },
  Kamala: {
    ru: 'Камала, Пхукет',
    en: 'Kamala, Phuket',
    zh: '卡马拉，普吉',
    th: 'กมลา, ภูเก็ต',
    match: ['kamala', 'камала', 'камала бич', '卡马拉', 'กมลา', 'หาดกมลา'],
  },
  Surin: {
    ru: 'Сурин / Пляж Сурин, Пхукет',
    en: 'Surin Beach, Phuket',
    zh: '苏林海滩，普吉',
    th: 'หาดสุรินทร์, ภูเก็ต',
    match: ['surin', 'сурин', 'сурин бич', '苏林', 'สุรินทร์', 'หาดสุรินทร์'],
  },
  'Bang Tao': {
    ru: 'Банг Тао, Пхукет',
    en: 'Bang Tao, Phuket',
    zh: '邦涛，普吉',
    th: 'บางเทา, ภูเก็ต',
    match: ['bang tao', 'bangtao', 'банг тао', 'бангтао', '邦涛', 'บางเทา', 'หาดบางเทา'],
  },
  'Nai Harn': {
    ru: 'Най Харн, Пхукет',
    en: 'Nai Harn, Phuket',
    zh: '奈汉，普吉',
    th: 'ในหาน, ภูเก็ต',
    match: ['nai harn', 'най харн', 'найхарн', '奈汉', 'ในหาน', 'หาดในหาน'],
  },
  Panwa: {
    ru: 'Панва, Пхукет',
    en: 'Panwa, Phuket',
    zh: '攀瓦，普吉',
    th: 'แหลมพันวา, ภูเก็ต',
    match: ['panwa', 'панва', 'cape panwa', 'кейп панва', '攀瓦', 'พันวา', 'แหลมพันวา'],
  },
  'Mai Khao': {
    ru: 'Май Кхао, Пхукет',
    en: 'Mai Khao, Phuket',
    zh: '迈考，普吉',
    th: 'ไม้ขาว, ภูเก็ต',
    match: ['mai khao', 'май кхао', 'майкао', '迈考', 'ไม้ขาว', 'หาดไม้ขาว'],
  },
  'Nai Yang': {
    ru: 'Най Янг, Пхукет',
    en: 'Nai Yang, Phuket',
    zh: '奈扬，普吉',
    th: 'ในยาง, ภูเก็ต',
    match: ['nai yang', 'най янг', '奈扬', 'ในยาง', 'หาดในยาง'],
  },
  'Phuket Town': {
    ru: 'Пхукет Таун / город Пхукет',
    en: 'Phuket Town',
    zh: '普吉镇',
    th: 'เมืองภูเก็ต',
    match: [
      'phuket town',
      'пхукет таун',
      'город',
      'old town',
      'старый город',
      '普吉镇',
      '老城',
      'เมืองเก่า',
      'เมืองภูเก็ต',
    ],
  },
  'Cape Panwa': {
    ru: 'Кейп Панва, Пхукет',
    en: 'Cape Panwa, Phuket',
    zh: '攀瓦角，普吉',
    th: 'แหลมพันวา, ภูเก็ต',
    match: ['cape panwa', 'кейп панва', 'panwa', '攀瓦角', 'แหลมพันวา'],
  },
  Cherngtalay: {
    ru: 'Чернгталай / Лагуна, Пхукет',
    en: 'Cherngtalay / Laguna, Phuket',
    zh: '承塔莱，普吉',
    th: 'เชิงทะเล, ภูเก็ต',
    match: ['cherngtalay', 'чернгталай', 'laguna', 'лагуна', 'laguna phuket', '承塔莱', 'เชิงทะเล'],
  },
  Thalang: {
    ru: 'Тхаланг, Пхукет',
    en: 'Thalang, Phuket',
    zh: '他朗，普吉',
    th: 'ถลาง, ภูเก็ต',
    match: ['thalang', 'тхаланг', '他朗', 'ถลาง'],
  },

  // —— Бангкок (если появятся в листингах) ——
  Sukhumvit: {
    ru: 'Сукхумвит, Бангкок',
    en: 'Sukhumvit, Bangkok',
    zh: '素坤逸，曼谷',
    th: 'สุขุมวิท, กรุงเทพฯ',
    match: ['sukhumvit', 'сукхумвит', '素坤逸', 'สุขุมวิท', 'asok', 'асок', 'nana', 'на на'],
  },
  Silom: {
    ru: 'Силом, Бангкок',
    en: 'Silom, Bangkok',
    zh: '是隆，曼谷',
    th: 'สีลม, กรุงเทพฯ',
    match: ['silom', 'силом', '是隆', 'สีลม'],
  },
  Sathorn: {
    ru: 'Сатхорн, Бангкок',
    en: 'Sathorn, Bangkok',
    zh: '沙吞，曼谷',
    th: 'สาทร, กรุงเทพฯ',
    match: ['sathorn', 'сатхорн', '沙吞', 'สาทร'],
  },
  'Khao San': {
    ru: 'Каосан, Бангкок',
    en: 'Khao San, Bangkok',
    zh: '考山路，曼谷',
    th: 'ข้าวสาร, กรุงเทพฯ',
    match: ['khao san', 'kaosan', 'каосан', '考山路', 'ข้าวสาร'],
  },
  Thonglor: {
    ru: 'Тонглор, Бангкок',
    en: 'Thonglor, Bangkok',
    zh: '通罗，曼谷',
    th: 'ทองหล่อ, กรุงเทพฯ',
    match: ['thonglor', 'thong lo', 'тонглор', '通罗', 'ทองหล่อ'],
  },
  Ekkamai: {
    ru: 'Эккамай, Бангкок',
    en: 'Ekkamai, Bangkok',
    zh: '亿甲迈，曼谷',
    th: 'เอกมัย, กรุงเทพฯ',
    match: ['ekkamai', 'эккамай', '亿甲迈', 'เอกมัย'],
  },
  'Pratunam': {
    ru: 'Пратунам, Бангкок',
    en: 'Pratunam, Bangkok',
    zh: '水门，曼谷',
    th: 'ประตูน้ำ, กรุงเทพฯ',
    match: ['pratunam', 'пратунам', '水门', 'ประตูน้ำ'],
  },

  // —— Паттайя / Чонбури ——
  Jomtien: {
    ru: 'Джомтьен, Паттайя',
    en: 'Jomtien, Pattaya',
    zh: '中天，芭堤雅',
    th: 'หาดจอมเทียน, พัทยา',
    match: ['jomtien', 'джомтьен', 'джомтьен бич', '中天', 'จอมเทียน', 'หาดจอมเทียน'],
  },
  Naklua: {
    ru: 'Наклуа, Паттайя',
    en: 'Naklua, Pattaya',
    zh: '那库阿，芭堤雅',
    th: 'นาเกลือ, พัทยา',
    match: ['naklua', 'наклуа', '那库阿', 'นาเกลือ'],
  },

  // —— Чиангмай ——
  Nimman: {
    ru: 'Нимман, Чиангмай',
    en: 'Nimman, Chiang Mai',
    zh: '宁曼，清迈',
    th: 'นิมมาน, เชียงใหม่',
    match: ['nimman', 'нимман', '宁曼', 'นิมมาน', 'nimmanhaemin'],
  },
  'Old City': {
    ru: 'Старый город, Чиангмай',
    en: 'Old City, Chiang Mai',
    zh: '古城，清迈',
    th: 'ในเมือง, เชียงใหม่',
    match: ['old city', 'старый город', '古城', 'ในเมือง', 'old town'],
  },

  // —— Краби / Ао Нанг ——
  'Ao Nang': {
    ru: 'Ао Нанг, Краби',
    en: 'Ao Nang, Krabi',
    zh: '奥南，甲米',
    th: 'อ่าวนาง, กระบี่',
    match: ['ao nang', 'aonang', 'ао нанг', '奥南', 'อ่าวนาง'],
  },
  Railay: {
    ru: 'Рейли, Краби',
    en: 'Railay, Krabi',
    zh: '莱利，甲米',
    th: 'ไร่เลย์, กระบี่',
    match: ['railay', 'railey', 'рейли', '莱利', 'ไร่เลย์'],
  },
}
