-- ========================================
-- Cleanup Demo/Test Listings
-- ========================================
-- Purpose: Remove demo and test listings, keeping only 4 clean examples
-- (one per category: Property, Motorbikes, Yachts, Tours)

-- Step 1: Display all current listings for review
SELECT 
  id,
  title,
  category_id,
  status,
  created_at,
  CASE 
    WHEN title ILIKE '%demo%' OR title ILIKE '%test%' OR id LIKE 'lst-test%' OR id LIKE '%demo%' THEN 'TO_DELETE'
    ELSE 'KEEP'
  END as action
FROM listings
ORDER BY category_id, created_at DESC;

-- Step 2: Identify listings to keep (4 best examples, one per category)
-- You can manually adjust these IDs based on the output above

-- Categories:
-- 1 = Property (Villa/Apartments)
-- 2 = Motorbikes  
-- 3 = Tours
-- 4 = Yachts

-- Step 3: Delete demo/test listings
-- IMPORTANT: Review the SELECT output above before running DELETE!

-- Delete listings with 'demo' or 'test' in title or ID
DELETE FROM listings
WHERE 
  title ILIKE '%demo%' 
  OR title ILIKE '%test%' 
  OR id LIKE 'lst-test%'
  OR id LIKE '%demo%'
  OR id LIKE 'lst-villa-%'  -- Generated by seed script
  OR id LIKE 'lst-yacht-%'  -- Generated by seed script
  OR id LIKE 'lst-mm%';      -- Test IDs with mm prefix

-- Step 4: Verify remaining listings (should be ~4 clean examples)
SELECT 
  id,
  title,
  category_id,
  status,
  owner_id,
  created_at
FROM listings
ORDER BY category_id, created_at DESC;

-- Step 5: (Optional) Keep specific high-quality listings by ID
-- If you want to keep specific listings, run this BEFORE the DELETE above:
-- Example:
-- UPDATE listings SET title = 'Beachfront Villa - Rawai' WHERE id = 'your-villa-id';
-- UPDATE listings SET title = 'Yamaha R15 - Sport Bike' WHERE id = 'your-bike-id';
-- UPDATE listings SET title = 'Luxury Yacht Charter' WHERE id = 'your-yacht-id';
-- UPDATE listings SET title = 'Island Hopping Tour' WHERE id = 'your-tour-id';

-- Verification: Count by category
SELECT 
  category_id,
  COUNT(*) as listing_count,
  STRING_AGG(title, ', ') as titles
FROM listings
GROUP BY category_id
ORDER BY category_id;
