/**
 * iOS PWA launch screens (apple-touch-startup-image).
 * Assets generated by scripts/build-brand-assets.py -> public/splash/.
 * device-width/height are CSS points; paired with -webkit-device-pixel-ratio.
 */
export function IosSplashLinks() {
  const screens = [
    [440, 956, 3], [430, 932, 3], [402, 874, 3], [393, 852, 3],
    [428, 926, 3], [390, 844, 3], [375, 812, 3], [414, 896, 3],
    [414, 896, 2], [375, 667, 2], [414, 736, 3],
  ]
  return (
    <>
      {screens.map(([lw, lh, dpr]) => (
        <link
          key={`${lw}-${lh}-${dpr}`}
          rel="apple-touch-startup-image"
          media={`screen and (device-width: ${lw}px) and (device-height: ${lh}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`}
          href={`/splash/apple-splash-${lw * dpr}-${lh * dpr}.png`}
        />
      ))}
    </>
  )
}

export default IosSplashLinks
